#!/usr/bin/env python
import os
import sys
import json
import subprocess


def main() -> None:
    """Assign Ruffs config depending on the branch in VSC Workspace."""
    vsc_config_filepath = os.path.join(
        '.vscode/', 'settings.json'
    )
    pre_commit_filepath = os.path.join(
        '.githooks', 'pre-commit'
    )

    # File checkout instead of branch checkout
    if not sys.argv[3]:
        return

    # Branch checkout
    new_branch = subprocess.run(
        ['git', 'symbolic-ref', '--short', 'HEAD'],
        stdout=subprocess.PIPE
    ).stdout.decode().strip()
    new_branch = new_branch if new_branch in ['dev', 'main'] else 'dev'

    # Replace text in VSC config
    with open(vsc_config_filepath) as configfile:
        txt = json.load(configfile)
    txt['ruff.configuration'] = f'lint/{new_branch}_ruff.toml'
    with open(vsc_config_filepath, 'w') as configfile:
        json.dump(txt, configfile, indent=4)

    # Replace text in pre-commit hook
    with open(pre_commit_filepath, 'r+') as configfile:
        if new_branch == 'dev':
            txt = configfile.read().replace('/main_', '/dev_')
        else:
            txt = configfile.read().replace('/dev_', '/main_')
        configfile.seek(0)
        configfile.write(txt)


if __name__ == '__main__':
    main()
