name: Deployment Pipeline

on:
  push:
    branches: [dev]

jobs:
  set_env_vars:
    name: Set environment variables
    runs-on: ubuntu-latest
    outputs: 
      SCRIPTS_PROJECT_ID: ${{ steps.env_vars.outputs.SCRIPTS_PROJECT_ID }}
      SCRIPTS_GCS: ${{ steps.env_vars.outputs.SCRIPTS_GCS }}
      DAG_PROJECT_ID: ${{ steps.env_vars.outputs.DAG_PROJECT_ID }}
      DAG_GCS: ${{ steps.env_vars.outputs.DAG_GCS }}
    steps:
      - id: 'env_vars'
        name: Setup enviroment
        shell: bash
        run: |-
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            branch=$(echo ${{ github.base_ref }} | tr / -)
          else
            branch=$(echo ${{ github.ref_name }} | tr / -)
          fi

          if [ $branch = "main" ]; then 
            scripts_project_id="cl-bigdata-analytics-prod";
            scripts_gcs="cl-bigdata-analytics-prod-us-dataproc-scripts";
            dag_project_id="cl-orquestador-prod";
            dag_gcs="us-east1-cl-orquestador-pro-df623903-bucket";
          elif [ $branch = "preprod" ]; then 
            scripts_project_id="cl-bigdata-analytics-preprod";
            scripts_gcs="cl-bigdata-analytics-preprod-us-dataproc-scripts";
            dag_project_id="cl-orquestador-preprod";
            dag_gcs="us-east1-cl-orquestador-pre-57dc49ea-bucket";
          elif [ $branch = "dev" ]; then 
            scripts_project_id="cl-bigdata-analytics";
            scripts_gcs="cl-bigdata-analytics-dev-us-dataproc-scripts";
            dag_project_id="cl-orquestador-preprod";
            dag_gcs="us-east1-cl-orquestador-pre-57dc49ea-bucket";
          else 
            echo "invalid environment"; exit -1
          fi
          echo "SCRIPTS_PROJECT_ID=$(echo $scripts_project_id)" >> $GITHUB_OUTPUT;
          echo "SCRIPTS_GCS=$(echo $scripts_gcs)" >> $GITHUB_OUTPUT;
          echo "DAG_PROJECT_ID=$(echo $dag_project_id)" >> $GITHUB_OUTPUT;
          echo "DAG_GCS=$(echo $dag_gcs)" >> $GITHUB_OUTPUT;


  gcs_upload_scripts:
    needs: [set_env_vars]
    if: ${{ github.event_name == 'push' }}
    name: Upload scripts
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'checkout'
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Set up secret file
        env:
            DEBUG_SERVICE_ACC: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
            echo $DEBUG_SERVICE_ACC >> src/secret.txt

      - id: auth
        name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Upload python commons to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          project_id: ${{ needs.set_env_vars.outputs.SCRIPTS_PROJECT_ID }}
          destination: ${{ needs.set_env_vars.outputs.SCRIPTS_GCS }}
          path: src
          glob: 'secret.txt'
          gzip: false
          parent: false
          process_gcloudignore: false
